#!/usr/bin/env python3
"""Generate a device's scenes.yaml from Govee's public app scene library.

Fetches the scene catalog for a SKU (name -> scene code + base64 scenceParam)
and writes it to devices/<sku>/scenes.yaml. Curated "working: false" flags are
preserved across regenerations (existing file wins), and a per-SKU seed of
known-broken scenes is applied on first generation.

Usage:
    python3 tools/fetch_scene_catalog.py --sku H60A6
"""
from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path

import yaml

LIBRARY_URL = "https://app2.govee.com/appsku/v1/light-effect-libraries"
APP_VERSION = "5.6.01"

# Curated knowledge: scenes that don't render correctly over BLE, by SKU.
# Applied on first generation; hand-edits in an existing scenes.yaml take
# precedence on regeneration.
BROKEN_SEED: dict[str, dict[str, str]] = {
    "H60A6": {
        "aurora": "0xFF placeholder header; fails to render over BLE",
        "dandelion": "0xFF placeholder header; fails to render over BLE",
        "desert": "0xFF placeholder header; fails to render over BLE",
        "fall": "0xFF placeholder header; fails to render over BLE",
        "green wheat field": "0xFF placeholder header; fails to render over BLE",
        "volcano": "0xFF placeholder header; fails to render over BLE",
        "ocean": "oversized scene; causes a BLE disconnect",
        "winter": "oversized scene; unreliable over BLE",
    },
}


def fetch(sku: str) -> list[dict]:
    url = f"{LIBRARY_URL}?sku={sku}"
    req = urllib.request.Request(url, headers={"AppVersion": APP_VERSION})
    with urllib.request.urlopen(req, timeout=20) as resp:  # noqa: S310 (trusted host)
        payload = json.load(resp)
    scenes: list[dict] = []
    for category in payload["data"]["categories"]:
        for scene in category.get("scenes", []):
            effects = scene.get("lightEffects") or []
            if not effects:
                continue
            eff = effects[0]
            scenes.append(
                {
                    "name": scene["sceneName"],
                    "code": int(eff["sceneCode"]),
                    "param": eff.get("scenceParam") or None,
                }
            )
    return scenes


def load_existing_flags(path: Path) -> dict[str, tuple[bool, str | None]]:
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    flags: dict[str, tuple[bool, str | None]] = {}
    for entry in data.get("scenes", []):
        if "working" in entry or "note" in entry:
            flags[entry["name"].casefold()] = (entry.get("working", True), entry.get("note"))
    return flags


def build_yaml(scenes: list[dict], sku: str, existing: dict) -> str:
    seed = BROKEN_SEED.get(sku.upper(), {})
    lines = [
        f"# Scene catalog for {sku}, generated by tools/fetch_scene_catalog.py",
        "# 'working: false' marks scenes that don't render correctly over BLE.",
        "scenes:",
    ]
    for s in scenes:
        key = s["name"].casefold()
        working: bool = True
        note: str | None = None
        if key in seed:  # first-generation curated knowledge
            working, note = False, seed[key]
        if key in existing:  # hand-edits win
            working, note = existing[key]
        entry: dict = {"name": s["name"], "code": s["code"]}
        if s["param"]:
            entry["param"] = s["param"]
        if not working:
            entry["working"] = False
        if note:
            entry["note"] = note
        # One scene per line (flow style, no wrapping) keeps the file scannable.
        dumped = yaml.safe_dump(entry, default_flow_style=True, sort_keys=False, width=10**9).strip()
        lines.append("  - " + dumped)
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sku", default="H60A6")
    ap.add_argument("--out", default=None, help="output scenes.yaml (default: packaged device folder)")
    args = ap.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    out = (
        Path(args.out)
        if args.out
        else repo_root / "src" / "govee_ble_local" / "devices" / args.sku.lower() / "scenes.yaml"
    )
    out.parent.mkdir(parents=True, exist_ok=True)

    scenes = fetch(args.sku)
    existing = load_existing_flags(out)
    out.write_text(build_yaml(scenes, args.sku, existing), encoding="utf-8")
    broken = sum(1 for s in scenes if s["name"].casefold() in BROKEN_SEED.get(args.sku.upper(), {}))
    print(f"Wrote {len(scenes)} scenes ({broken} flagged broken) to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
